API-6945-reject-unknown-modifiers
department-of-veterans-affairs/lighthouse-vulcan pull request #15
Opened 2021-05-06 18:57 UTC by jhulbert-va

# [API-6945](https://vajira.max.gov/browse/API-6945)
This PR moves the reject unknown modifier logic out of the allergy intolerance controller in dq so that it can be used in all controllers. In addition, this adds missing support for the 'identifier' modifier on reference parameters by default.

2021-05-06 19:25 UTC, jabando-va approved these changes

2021-05-06 21:07 UTC, bschofield-va requested changes
hol up... lemme go read that spec.

2021-05-06 21:13 UTC, bschofield-va commented on src/main/java/gov/va/api/lighthouse/vulcan/Rules.java
> +     */
http://hl7.org/fhir/R4/search.html#errors
I think this implementation is correct for _strict_ processing but not _lenient_

2021-05-06 21:18 UTC, bschofield-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceMapping.java
> +            Stream.of(parameterName(), parameterName() + ":identifier"),
where's my test for `:identifier`

2021-05-06 21:20 UTC, jhulbert-va commented on src/main/java/gov/va/api/lighthouse/vulcan/Rules.java
> +     */
The problem I'm trying to solve here is the following. For a `patient` reference parameter where only the patient resource type is allowed, the behavior is as follows: 
```
patient=123                                      records
patient=Patient/123                          records
patient=url/r4/Patient/123                 records
patient:Patient=123                          records
patient=RelatedPerson/456              400
patient=url/r4/RelatedPerson/456     400
patient:RelatedPerson=456              emptyBundle
```

For the first four, that would be my expectation. However, for the last three, one of them is incorrect. This method was meant to allow us to make the last case behave the same as the other two do.

2021-05-06 21:20 UTC, bschofield-va commented on src/main/java/gov/va/api/lighthouse/vulcan/Rules.java
> +                .collect(toList());
`toSet` is faster. `List.contains()` will do a sequential search.

2021-05-06 21:22 UTC, bschofield-va commented on src/main/java/gov/va/api/lighthouse/vulcan/Rules.java
> +     */
This is fine for now, because we don't even acknowledge `Prefer: handling=strict|lenient` header at this time

2021-05-06 22:22 UTC, jhulbert-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceMapping.java
> +            Stream.of(parameterName(), parameterName() + ":identifier"),
While writing the test, I found that dealing with the identifier modifier is more nuanced than I initially thought. The way that ReferenceParameter is written, more than one modifier can't be supported at a time or it _always_ required a modifier in the search, breaking our current expected behavior. I will create a task to revisit this later as it is not functionality we already have and is thus not in the critical flow of things. Until then, I have removed it from this PR.

2021-05-07 13:08 UTC, bschofield-va approved these changes

2021-05-07 13:08 UTC, merged