Combine same field values with 'In' instead of 'Or'
department-of-veterans-affairs/lighthouse-vulcan pull request #32
Opened 2022-10-17 18:11 UTC by KevinCranmer

2022-10-17 22:55 UTC, jblefkove-va requested changes

2022-10-17 22:55 UTC, jblefkove-va commented on src/main/java/gov/va/api/lighthouse/vulcan/Specifications.java
> +      mas.silSpecifications.values().forEach(this::add);
include a null check for `mas`

2022-10-17 22:55 UTC, jblefkove-va commented on src/main/java/gov/va/api/lighthouse/vulcan/Specifications.java
> +        silSpecifications.values().forEach(specification::or);
`silSpecifications` is guaranteed to be non-null, so you don't need the emptiness check; `specification` may be null though

2022-10-17 22:55 UTC, jblefkove-va commented on src/main/java/gov/va/api/lighthouse/vulcan/Specifications.java
> +                new SelectInListSpecification<>(
Can we move this into an `add(silSpec)` method on `SpecificationInList`?

2022-10-17 22:55 UTC, jblefkove-va commented on src/main/java/gov/va/api/lighthouse/vulcan/Specifications.java
>      MatchesAnySpecifications<E> add(Specification<E> orMe) {
`orMe` is no longer an appropriate parameter name

2022-10-17 22:55 UTC, jblefkove-va commented on src/main/java/gov/va/api/lighthouse/vulcan/SelectInListSpecification.java
> +  private final @NonNull String fieldName;
Put the annotation out front

2022-10-17 22:55 UTC, jblefkove-va commented on src/main/java/gov/va/api/lighthouse/vulcan/SelectInListSpecification.java
> +public class SelectInListSpecification<T> implements Specification<T> {
This class can be `@Value`

2022-10-17 22:55 UTC, jblefkove-va commented on src/main/java/gov/va/api/lighthouse/vulcan/SelectInListSpecification.java
> +public class SelectInListSpecification<T> implements Specification<T> {
This can be another inner class in `Specifications`

2022-10-17 22:55 UTC, jblefkove-va commented on src/main/java/gov/va/api/lighthouse/vulcan/Specifications.java
>        if (orMe != null) {
We can simplify this flow more:
```
if (other == null) {
  return this;
}
if (other instanceof SelectInListSpecification<E> silSpec) {
  // add silSpec to map
  return this;
}
specification = specification != null ? specification.or(other) : other;
return this;
```

2022-10-18 00:03 UTC, KevinCranmer commented on src/main/java/gov/va/api/lighthouse/vulcan/Specifications.java
> +                new SelectInListSpecification<>(
I added `append()` to `MatchesAnySpecifications` because I didn't want to add another `add()` method since others with other purposes already exist. And I'm not sure what class was meant by `SpecificationInList`, I don't think we want it in `SetInListSpecification` because we're adding to a variable in `MatchesAnySpecifications`

2022-10-18 00:04 UTC, KevinCranmer commented on src/main/java/gov/va/api/lighthouse/vulcan/Specifications.java
>        if (orMe != null) {
I had to add some extra stuff to use `SelectInListSpecification` and idk if the `?` syntax is worth it now because it's a little messy

2022-10-18 00:08 UTC, KevinCranmer commented on src/main/java/gov/va/api/lighthouse/vulcan/Specifications.java
> +        silSpecifications.values().forEach(specification::or);
Removing emptiness check causes a test to fail:
```
java.lang.NullPointerException
        at gov.va.api.lighthouse.vulcan.SpecificationsTest.collectAny(SpecificationsTest.java:50)
```

2022-10-18 01:09 UTC, jblefkove-va commented on src/main/java/gov/va/api/lighthouse/vulcan/Specifications.java
> +        silSpecifications.values().forEach(specification::or);
That NPE is from `specification` being null though, not `silSpecifications`. Also, looking at this again, I realize that this method is modifying `specification`, which is also not ideal. How about:

```
var result = specification;
for (var s : silSpecifications.values()) {
  result = s.or(result);
}
return result;
```

2022-10-18 01:11 UTC, jblefkove-va commented on src/main/java/gov/va/api/lighthouse/vulcan/Specifications.java
> +                  Stream.concat(addIn.values().stream(), spec.values().stream())
You don't need this check, it is a duplicate of the `append()` method. In essence, if the parameter spec is a `SelectInListSpecification()`, you execute `append()` above to update the map and then return; otherwise, execute the existing OR logic

2022-10-18 01:13 UTC, jblefkove-va commented on src/main/java/gov/va/api/lighthouse/vulcan/Specifications.java
> +                new SelectInListSpecification<>(
To clarify, this is what I envisioned:

```
var mapped = silSpecifications.get(addIn.fieldName());
silSpecifications.put(addIn.fieldName(), addIn.add(mapped));
```

2022-10-18 12:14 UTC, jblefkove-va commented on src/main/java/gov/va/api/lighthouse/vulcan/Specifications.java
>      @Getter Specification<E> specification;
Move `@Getter` to the class-level so it also applies to `silSpecifications`

2022-10-18 12:17 UTC, jblefkove-va commented on src/main/java/gov/va/api/lighthouse/vulcan/Specifications.java
> +        mas.silSpecifications.values().forEach(this::add);
Use getters for accessing the fields on `mas`

2022-10-18 12:17 UTC, jblefkove-va commented on src/main/java/gov/va/api/lighthouse/vulcan/Specifications.java
> +    public SelectInListSpecification<T> add(SelectInListSpecification<T> silSpec) {
`add(other)` for the parameter name to match `MatchesAnySpecification`

2022-10-18 12:19 UTC, jblefkove-va commented on src/main/java/gov/va/api/lighthouse/vulcan/Specifications.java
> +      if (silSpec != null) {
This method is cleaner with the conditional swapped, i.e. `if parameter is null, bail immediately, otherwise continue building new SelectInListSpecification`

2022-10-18 12:19 UTC, jblefkove-va commented on src/main/java/gov/va/api/lighthouse/vulcan/Specifications.java
> +        CriteriaBuilder.In<Object> in = criteriaBuilder.in(root.get(fieldName));
var

2022-10-18 12:27 UTC, jblefkove-va commented on src/test/java/gov/va/api/lighthouse/vulcan/SpecificationsTest.java
> +    assertThat(Specifications.selectInList("category", List.of())).isNull();
Do we also want a test for the non-null case?

2022-10-18 15:37 UTC, merged