reference parameter intial implementation
department-of-veterans-affairs/lighthouse-vulcan pull request #8
Opened 2021-01-15 14:48 UTC by ilaflamme-va

2021-01-15 15:57 UTC, bschofield-va commented on README.md
> +Notes:
these notes need to be cleaned into something a little more developer friendly to someone not on our team?

2021-01-15 16:01 UTC, bschofield-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceParameter.java
> +              parameterName, parameterValue, "Reference URL is not parsable.");
Error message should include more help on how a developer could fix the problem. _Why is the URL not parsable?_

2021-01-15 16:06 UTC, bschofield-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceParameter.java
> +        .type(parameterName)
this doesn't work. the resource type isn't `patient`, it's `Patient`

2021-01-15 16:13 UTC, bschofield-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceParameter.java
> +              parameterName, parameterValue, "Reference URL is not parsable.");
Instead of a having a series of if/else, I'd rather see loop of known formatters attempting to parse it.

```
interface Format {
  ReferenceParameter tryParse(String value);
  String help();
}
```

```
private static final Collection<Format> SUPPORTED_FORMATS = List.of(
   new AbsoluteUrlFormat(), 
   new RelativeUrlFormat(),
   new ResourceTypeAndValueFormat(),
   new ValueOnlyFormat() <-- tricky
```

```
public static ReferenceParameter parse(value) {
  for( Format f: SUPPORTED_FORMATS) {
     var ref = f.tryParse( parameterValue )
     if ( ref != null ) { return ref; }
  }
  throw helpful message on supported formats by collecting help from each format
}
```

2021-01-15 19:38 UTC, jhulbert-va reviewed
Usage and Fugazi tests?

2021-01-15 19:38 UTC, jhulbert-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/Mappings.java
> +      Predicate<ReferenceParameter> isSupported,
Nitpick: To keep with the other mappings, this would be `supportedReference`

2021-01-15 19:38 UTC, jhulbert-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceMapping.java
> +  private Stream<String> asParameterWithType() {
Nitpick: `asParametersWithTypeModifier` might better describe what this is doing.

2021-01-15 19:38 UTC, jhulbert-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceParameter.java
> +  String publicId;
What do we buy ourselves from having both `value` and `publicId`? These fields are immutable (Value annotation), so they'll always be the same value right?

2021-01-15 19:38 UTC, jhulbert-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceParameter.java
> +    ReferenceParameter tryParse(String parameterName, String parameterValue);
Should this return an `Optional`? That way we can check for empty instead of null.

2021-01-15 19:38 UTC, jhulbert-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceParameter.java
> +  private static class ResourceTypeAndValueFormat implements ReferenceFormat {
Nitpick: `TypeModifierAndValueFormat`?

2021-01-15 19:40 UTC, jhulbert-va commented on src/test/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceParameterTest.java
> +        Arguments.of("patient", "123", "Patient", "123", "123", null),
Can you comment on the meaning of each value above the return statement? e.g.
```
// parameter, value, expectedType...
```

2021-01-20 17:10 UTC, bschofield-va commented on src/test/java/gov/va/api/lighthouse/vulcan/VulcanTest.java
> +    // TODO: all reference formats
more coming?

2021-01-20 17:14 UTC, bschofield-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceParameterParser.java
> +      return "ValueOnly format: ?reference=id";
`ValueOnly format:` doesn't really add value to the user. They only care about _parameter=id_
This applies to all of the help methods and I think you should use the same parameter example name in all them, vs _reference_ in one and _param_ another and _parameter_ in a third.

2021-01-20 17:14 UTC, ilaflamme-va commented on src/test/java/gov/va/api/lighthouse/vulcan/VulcanTest.java
> +    // TODO: all reference formats
Yep, more in the works.

2021-01-20 17:15 UTC, ilaflamme-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceParameterParser.java
> +      return "ValueOnly format: ?reference=id";
Thanks, I was struggling with what would be the best help message.

2021-01-20 17:16 UTC, bschofield-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceParameterParser.java
> +      return "ValueOnly format: ?reference=id";
That said, if you want to add more help text, great, just don't use class names, e.g.
```
(value only) parameter=id,
(type and value) parameter=ResourceType/id,
...
```

2021-01-20 17:17 UTC, bschofield-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceParameter.java
> +  String publicId;
no, they will not, value will be the full parameter value, e.g. a URL or type/id. ID is parsed ID from the value.

2021-01-20 17:53 UTC, bschofield-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceParameterParser.java
> +  private final String parameterName;
You've built in circular dependencies. ReferenceParameterParse has the variables for each Format class? Make the formats _static_ and fix all the breakages. They're all tangled together.

2021-01-20 17:56 UTC, bschofield-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceParameterParser.java
> +                parameterName, parameterValue, "Reference URL is not parsable.");
explain why... help the poor schmuck developer know what's wrong

2021-01-20 17:58 UTC, bschofield-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceParameterParser.java
> +      if (parameterValue.matches("^[a-zA-Z]*/[a-zA-Z0-9]*$")) {
`I2-123` won't parse... neither will any UUID. This is not compatible with https://www.hl7.org/fhir/datatypes.html#id

2021-01-20 18:00 UTC, bschofield-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceParameterParser.java
> +      if (allowedReferenceTypes.size() > 1) {
Why does the value format care about the allowed types?

2021-01-20 18:00 UTC, bschofield-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceParameterParser.java
> +        resourceType = parameterName;
why is the parameter name the resource type?

2021-01-20 18:02 UTC, bschofield-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceParameterParser.java
> +    ReferenceParameter tryParse();
Not an extensible interface... no implementation of ReferenceFormat that is not a non-static inner class can ever be created.
`tryParse(String value)`

2021-01-20 18:04 UTC, bschofield-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceMapping.java
> +  private String asStartsWithParameterName() {
why "starts with"? References have no "starts with" semantics.

2021-01-20 18:06 UTC, bschofield-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceMapping.java
> +    if (!referenceParameter.type().isBlank()
Why doesn't `parse()` throw the exception. If it cannot determine the type, then value is bad.

2021-01-20 18:10 UTC, bschofield-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceMapping.java
> +  Set<String> allowedReferenceTypes;
Wonder if this would be better as _allowedResourceTypes_ to better match _defaultResourceType_. Could someone mistakenly interpret "reference type" to be "format"?

2021-01-20 18:14 UTC, bschofield-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceMapping.java
> +    if (supportedReference().test(referenceParameter)) {
You know the allowed resource types, that should be checked here before invoking supportedReference

2021-01-20 18:18 UTC, bschofield-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceMapping.java
> +    if (supportedReference().test(referenceParameter)) {
^ is this true? I'm not sure it is and pretty sure I can talk myself out it...

I allow "Practitioner" and "Organization" per the spec, but I only can support searching on "Practitioner".

2021-01-20 19:03 UTC, ilaflamme-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceParameterParser.java
> +      if (parameterValue.matches("^[a-zA-Z]*/[a-zA-Z0-9]*$")) {
Ok, I've replaced the reg-ex.

2021-01-20 19:22 UTC, ilaflamme-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceMapping.java
> +    if (supportedReference().test(referenceParameter)) {
I think that the `parse()` is responsible for making sure it is an _allowedReferenceType_ as per the spec and that `supportedReference()` is resonsible for "I can only support Practitioner searching."

2021-01-20 19:24 UTC, ilaflamme-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceMapping.java
> +  Set<String> allowedReferenceTypes;
Ok, I can get behind the idea that a _reference=resourcetype + id_

2021-01-20 20:13 UTC, bschofield-va commented on src/test/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceParameterParserTest.java
> +    return Stream.of(
I'd like to see a test with multiple allowed resources

2021-01-25 15:40 UTC, bschofield-va requested changes

2021-01-25 20:50 UTC, bschofield-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceParameterParser.java
> +      if (!allowedReferenceTypes.contains(ref.type())) {
noting that `allowedReferenceTypes` is not `@NonNull` this could NPE

2021-01-25 20:51 UTC, bschofield-va commented on src/test/java/gov/va/api/lighthouse/vulcan/VulcanTest.java
> +    return // pages of results
noting formatting is weird, those `// inline` comments strike again!

2021-01-25 20:53 UTC, bschofield-va commented on src/test/java/gov/va/api/lighthouse/vulcan/fugazi/FugaziController.java
> +        referenceParameter.url());
Pretty sure `url()` is going to print something like `java.whatever.Optional@231243`

2021-01-25 20:53 UTC, bschofield-va submitted a review, later dismissed

2021-01-25 20:54 UTC, jblefkove-va commented on src/test/java/gov/va/api/lighthouse/vulcan/VulcanTest.java
> +    return // pages of results
👎 trailing comments

2021-01-25 21:31 UTC, bschofield-va commented on src/test/java/gov/va/api/lighthouse/vulcan/fugazi/FugaziController.java
> +        referenceParameter.url().isPresent() ? referenceParameter.url().get() : "no url");
No change necessary, we've moved into nit picking, but in the future, this can be simplified as

`referenceParameter.url().orElse("no url")`

2021-01-25 21:32 UTC, bschofield-va commented on src/test/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceParameterParserTest.java
> +  void invalidRequest(
_invalid_

gotten!

2021-01-25 21:32 UTC, bschofield-va submitted a review, later dismissed

2021-01-25 21:35 UTC, ilaflamme-va commented on src/main/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceMapping.java
> +    return isNotBlank(request.getParameter(parameterName()))
No reason.

2021-01-25 21:36 UTC, ilaflamme-va commented on src/test/java/gov/va/api/lighthouse/vulcan/fugazi/ExampleUsage.java
> +                .reference(
Seems fine to me. I can use different terms if you really want it.

2021-01-25 21:36 UTC, ilaflamme-va commented on src/test/java/gov/va/api/lighthouse/vulcan/mappings/ReferenceParameterParserTest.java
> +  void invalidRequest(
Yea, probably a better name here.

2021-01-25 22:09 UTC, jhulbert-va approved these changes

2021-01-25 22:14 UTC, bschofield-va approved these changes

2021-01-25 22:18 UTC, merged